version: "3"
services:
  mongo0:
    hostname: mongo0
    container_name: mongo0
    image: mongo:3.6
    ports:
      - 27017:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  mongo1:
    hostname: mongo1
    container_name: mongo1
    image: mongo:3.6
    ports:
      - 27018:27018
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--port", "27018","--bind_ip_all", "--replSet", "rs0" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  mongo2:
    hostname: mongo2
    container_name: mongo2
    image: mongo:3.6
    ports:
      - 27019:27019
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--port", "27019","--bind_ip_all", "--replSet", "rs0" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  create-replica-set:
    image: mongo:3.6
    depends_on:
      - mongo0
      - mongo1
      - mongo2
    restart: "no"
    volumes:
      - .:/var/tmp/
    entrypoint: [ "/bin/bash", "/var/tmp/execute-mongo-script.sh", "/var/tmp/create-replica-set.js"]



